version: "1.0"

indicators:
  - image: &runner saicoss/tmp:cac262abf04707d67167e7f3af561a7ab9381a8f

stages:
  - "clone"
  - "deliver"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  deliver:
    title: "Delivering artifact(s)"
    type: "freestyle"
    image: *runner
    working_directory: "${{clone}}"
    stage: "deliver"
    commands:
      - asdf install
      - task deliver
