version: "1.0"

indicators:
  - image: &runner saicoss/anvil:0.5.6

stages:
  - "clone"
  - "validate"
  - "test"
  - "secure"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  validate:
    title: "Validating project"
    type: "freestyle"
    image: *runner
    working_directory: "${{clone}}"
    stage: "validate"
    environment:
      - "PRE_COMMIT_HOME=/codefresh/volume/pre-commit-cache"
    commands:
      - asdf install
      - task validate

  test:
    title: "Running automated tests"
    type: "freestyle"
    image: *runner
    working_directory: "${{clone}}"
    stage: "test"
    commands:
      - asdf install
      - task test

  secure:
    title: "Running automated security checks"
    type: "freestyle"
    image: *runner
    working_directory: "${{clone}}"
    stage: "secure"
    commands:
      - asdf install
      - task secure
